namespace AOC2025Tests.Puzzles;

public class Day07Test
{
    private static readonly string _testInput1 = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""";

    [Test]
    public void Solve1Test()
    {
        var day = new Day07(_testInput1.Split("\n", StringSplitOptions.TrimEntries));
        _ = day.Solve1().Should().Be(21);
    }

    [Test]
    public void Solve2Test()
    {
        var day = new Day07(_testInput1.Split("\n", StringSplitOptions.TrimEntries));
        _ = day.Solve2().Should().Be(40);
    }
}
