namespace AOC2024Tests.Puzzles;

public class Day08Test
{
    private static readonly string _testInput1 = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""";

    private static readonly string _testInput2 = """
T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
..........
""";

    [Test]
    public void Solve1Test()
    {
        var day = new Day08(_testInput1.Split("\n", StringSplitOptions.TrimEntries));
        _ = day.Solve1().Should().Be(14);
    }

    [Test]
    public void Solve2Test()
    {
        var day = new Day08(_testInput1.Split("\n", StringSplitOptions.TrimEntries));
        _ = day.Solve2().Should().Be(34);
    }

    [Test]
    public void Solve2aTest()
    {
        var day = new Day08(_testInput2.Split("\n", StringSplitOptions.TrimEntries));
        _ = day.Solve2().Should().Be(9);
    }
}
